title: "pit notes & reviews"
author: "monet"
description: "local london skramz, emo, punk, hardcore, p-hardcore gig highlights and reviews"
github_username: "m0nets"
youtube_username: ""


#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
